export const projects = [
  {
    mode: 0,
    class: "Scheduling Web App",
    title: "Apollo Appointment Scheduler",
    description: "Apollo is a full stack web app to book and track appointments with clients.",
    demoLink: "https://apollo-appointment-scheduler-evptp4uhp-jamalfox85.vercel.app/login",
    githubLink: "https://github.com/Jamalfox85/Apollo_Appointment_Scheduler",
    skills: ["Vue", "HTML", "CSS", "Sass", "Bootstrap", "PHP"],
  },
  {
    mode: 1,
    class: "Finance Web App",
    title: "Tauro Finance",
    description: "Tauro Finance is a full stack web app to manage and track finances including bills, credit score details, debt, and savings goals.",
    demoLink: "https://lustrous-scone-98a9c1.netlify.app/",
    githubLink: "https://github.com/Jamalfox85/financial-dashboard",
    skills: ["Vue", "HTML", "CSS", "Sass", "Tailwind", "Supabase"],
    login: true,
  },
  {
    mode: 2,
    class: "Web",
    title: "Fast Box",
    description: "This project is a landing page for a food delivery company. The design is based off a mockup found on dribbble from ",
    demoLink: "https://63d07cea8aa02a6000e23911--adorable-eclair-87951b.netlify.app/",
    githubLink: "https://github.com/Jamalfox85/fast-box",
    skills: ["Vue", "Nuxt", "HTML", "CSS", "Sass"],
  },
];
